name: Deploy to Production

on:
  push:
    #branches:
      #- master  # This triggers the workflow on pushes to the develop branch
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
      # - '*'  # This triggers the workflow on develop tag push
      
jobs:  
  build-and-push:
    if: startsWith(github.ref, 'refs/tags/') && github.ref_type == 'tag' && github.base_ref == 'master'  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-cekip:${{ github.ref_name }}
