name: Build and Push to Artifact Registry

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  APP_NAME: "cicd-nginx-cekip"
  GCP_ARTIFACT_REGISTRY: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_NAME }}"
  
jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        
      - name: "Auth"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.GCP_ARTIFACT_REGISTRY }}/${{ env.APP_NAME }}

      - name: Push image
        run: docker push ${{ env.GCP_ARTIFACT_REGISTRY }}/${{ env.APP_NAME }}
