name: Build and Push to Artifact Registry

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    env:
      APP_NAME: cicd-nginx-cekip
      GCP_ARTIFACT_REGISTRY: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_PROJECT_NAME }}/${{ env.APP_NAME }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        
      - name: "Auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.GCP_ARTIFACT_REGISTRY }}

      - name: Push image
        run: docker push ${{ env.GCP_ARTIFACT_REGISTRY }}
