name: Deploy to Production

on:
  push:
    #branches:
      #- master  # This triggers the workflow on pushes to the master branch
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
      # - '*'  # This triggers the workflow on master tag push
      
jobs:
  determine-base-branch:
    runs-on: ubuntu-latest
    outputs:
      is_master_branch: ${{ steps.check_branch.outputs.is_master_branch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the branch name
        id: check_branch
        run: |
          # Get the commit SHA for the tag
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          # Get the branches containing the commit
          BRANCHES=$(git branch -r --contains $TAG_COMMIT)
          # Check if one of the branches is master
          if echo "$BRANCHES" | grep -q "origin/master"; then
            echo "::set-output name=is_master_branch::true"
          else
            echo "::set-output name=is_master_branch::false"
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: determine-base-branch
    if: needs.determine-base-branch.outputs.is_master_branch == 'true'
    
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-cekip:${{ github.ref_name }}
